version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nitpick
    versions:
    - 0.24.0
  - dependency-name: wemake-python-styleguide
    versions:
    - 0.15.0
  - dependency-name: mypy
    versions:
    - "0.800"
- package-ecosystem: pip
  directory: "/docs/requirements.txt‎"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
